### ISSUE TITLE
Argument labels '(describing:)' do not match any available overloads

### ISSUE THREAD

**Issue by chansuke** [AcroMace/receptionkit#26]
I only changed `AppToken` in Config.swift and put `#import <Smooch/Smooch.h>` in Bridging-Header but several error occurs.

```
ReceptionKit/View Controllers/Visitor/VisitorAskNameViewController.swift:47:19: Method does not override any method from its superclass
```

```
ReceptionKit/View Controllers/Delivery/DeliveryMethodViewController.swift:69:19: Method does not override any method from its superclass
```

```
ReceptionKit/View Controllers/Delivery/DeliveryMethodViewController.swift:69:19: Method cannot be an @objc override because the type of the parameter 2 cannot be represented in Objective-C
```

I am using Swift3 and Xcode-beta8.0

**Comment by AcroMace** [comment]
Hey @chansuke! Sorry for not seeing this earlier. It looks like this might be related to a Swift 3 compatibility issue here: https://github.com/smooch/smooch-ios/issues/111#issuecomment-249232785. I'll try updating Smooch to 5.0.1.

**Comment by AcroMace** [comment]
Hey @chansuke, this should be fixed in the latest master. Would you mind confirming if it works correctly for you? You shouldn't have to modify the Bridging-Header file.

**Comment by chansuke** [comment]
@AcroMace Thank you.

**Comment by chansuke** [comment]
@AcroMace I pulled newest verion(updated to Smooch 5.0.1) but still doesn't work...

<img width="705" alt="reception_kit" src="https://cloud.githubusercontent.com/assets/501052/19181717/ef64024a-8ca9-11e6-97be-6e4283a3136e.png">

**Comment by chansuke** [comment]
@AcroMace I updated to Xcode8 and everything work fine.Thank you.

**Comment by AcroMace** [comment]
@chansuke Oh awesome, thanks for the update!
